package cz.zcu.kiv.crce.classmodel.definition;

public enum ArgConfigType {
    POST, GET, PUT, PATCH, DELETE, HEAD, OPTIONS, TRACE, PATH, EXPECT, SKIP, PARAM, PARAMKEY,

    PARAMVALUE, BASEURL, SEND, EXCHANGE, HTTPMETHOD, CONTENTTYPE, ACCEPT, HEADERTYPE, HEADERVALUE, EDATA
}
